// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TtssHis.Shared.DbContexts;

#nullable disable

namespace TtssHis.Database.Migrations.Migrations
{
    [DbContext(typeof(HisDbContext))]
    [Migration("20260327164557_Phase5Lab")]
    partial class Phase5Lab
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TtssHis.Shared.Entities.Billing.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Running number: INVyyyyMMddNNNNN");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("PENDING=1, PAID=2, CANCELED=9");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId")
                        .IsUnique();

                    b.HasIndex("InvoiceNo")
                        .IsUnique();

                    b.ToTable("Invoices", t =>
                        {
                            t.HasComment("ใบแจ้งหนี้");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Billing.InvoiceItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrugOrderItemId")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Billing.Receipt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasComment("CASH=1, CARD=2, TRANSFER=3");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Running number: RCyyyyMMddNNNNN");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.HasIndex("ReceiptNo")
                        .IsUnique();

                    b.ToTable("Receipts", t =>
                        {
                            t.HasComment("ใบเสร็จรับเงิน");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.Division", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("รหัสแผนก (UUID)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("รหัสย่อแผนก เช่น OPD, LAB");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อแผนก (ไทย)");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasComment("ชื่อแผนก (อังกฤษ)");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("ประเภท: OPD=1, IPD=2, ER=3, PHARMACY=4, LAB=5, BILLING=6, OTHER=9");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedDate\" IS NULL");

                    b.ToTable("Divisions", t =>
                        {
                            t.HasComment("แผนก/หน่วยงาน");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.Doctor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("รหัสแพทย์ (UUID)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อ (ไทย)");

                    b.Property<string>("FirstNameEn")
                        .HasColumnType("text")
                        .HasComment("ชื่อ (อังกฤษ)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasComment("เพศ: M=1, F=2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("นามสกุล (ไทย)");

                    b.Property<string>("LastNameEn")
                        .HasColumnType("text")
                        .HasComment("นามสกุล (อังกฤษ)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text")
                        .HasComment("รหัสใบประกอบวิชาชีพ");

                    b.Property<string>("PreName")
                        .HasColumnType("text")
                        .HasComment("คำนำหน้า (ไทย)");

                    b.Property<string>("PreNameEn")
                        .HasColumnType("text")
                        .HasComment("คำนำหน้า (อังกฤษ)");

                    b.Property<string>("Specialty")
                        .HasColumnType("text")
                        .HasComment("ความเชี่ยวชาญ");

                    b.HasKey("Id");

                    b.ToTable("Doctors", t =>
                        {
                            t.HasComment("แพทย์");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("รหัสบทบาท");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("รายละเอียด");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อบทบาท");

                    b.HasKey("Id");

                    b.ToTable("Roles", t =>
                        {
                            t.HasComment("บทบาทผู้ใช้งาน");
                        });

                    b.HasData(
                        new
                        {
                            Id = "role-doctor",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "แพทย์",
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = "role-nurse",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "พยาบาล",
                            Name = "Nurse"
                        },
                        new
                        {
                            Id = "role-pharmacist",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "เภสัชกร",
                            Name = "Pharmacist"
                        },
                        new
                        {
                            Id = "role-finance",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "การเงิน",
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("รหัสผู้ใช้งาน");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorId")
                        .HasColumnType("text")
                        .HasComment("รหัสแพทย์ (ถ้าเป็นหมอ)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อจริง");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("นามสกุล");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("รหัสผ่าน (bcrypt hash)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("รหัสบทบาท");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้ใช้งาน (login)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"DeletedDate\" IS NULL");

                    b.ToTable("Users", t =>
                        {
                            t.HasComment("ผู้ใช้งานระบบ");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Encounter.Diagnosis", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icd10Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("ประเภท: PRINCIPAL=1, COMORBIDITY=2, COMPLICATION=3, RULE_OUT=4");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.HasIndex("Icd10Id");

                    b.ToTable("Diagnoses", t =>
                        {
                            t.HasComment("การวินิจฉัยโรค");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Encounter.Encounter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BedNumber")
                        .HasColumnType("text")
                        .HasComment("เตียง (สำหรับ IPD)");

                    b.Property<string>("ChiefComplaint")
                        .HasColumnType("text")
                        .HasComment("อาการสำคัญ");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorId")
                        .HasColumnType("text");

                    b.Property<string>("EncounterNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("เลข Visit (running number)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("สถานะ: OPEN=1, ADMITTED=2, DISCHARGED=3, CLOSED=4, CANCELED=9");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("ประเภท: OPD=1, IPD=2, ER=3, SS=4");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("EncounterNo")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("Encounters", t =>
                        {
                            t.HasComment("Visit ผู้ป่วย (OPD/IPD)");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Er.ErTriage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ArrivalMode")
                        .HasColumnType("integer")
                        .HasComment("วิธีมาถึง: WALK=1, AMBULANCE=2, REFER=3, OTHER=9");

                    b.Property<int?>("Disposition")
                        .HasColumnType("integer")
                        .HasComment("การส่งต่อ: DISCHARGE=1, ADMIT=2, REFER=3, DECEASED=9");

                    b.Property<DateTime?>("DispositionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasComment("ระดับความเร่งด่วน: P1=Critical=1, P2=Urgent=2, P3=SemiUrgent=3, P4=NonUrgent=4");

                    b.Property<string>("TriageBy")
                        .HasColumnType("text");

                    b.Property<string>("TriageNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("TriageTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId")
                        .IsUnique();

                    b.HasIndex("Severity", "TriageTime");

                    b.ToTable("ErTriages", t =>
                        {
                            t.HasComment("การคัดกรองผู้ป่วยฉุกเฉิน");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Insurance.Coverage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("ประเภทสิทธิ: GOVERNMENT=1, PRIVATE=2, SELF_PAY=3, EMPLOYEE=4");

                    b.HasKey("Id");

                    b.ToTable("Coverages", t =>
                        {
                            t.HasComment("สิทธิการรักษา");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Insurance.Payer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverageId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoverageId");

                    b.ToTable("Payers", t =>
                        {
                            t.HasComment("ผู้รับผิดชอบค่าใช้จ่าย (บริษัทประกัน / ภาครัฐ)");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Ipd.Bed", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BedNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentEncounterId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("AVAILABLE=1, OCCUPIED=2, MAINTENANCE=3");

                    b.Property<string>("WardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentEncounterId")
                        .IsUnique()
                        .HasFilter("\"CurrentEncounterId\" IS NOT NULL");

                    b.HasIndex("WardId", "BedNo")
                        .IsUnique();

                    b.ToTable("Beds", t =>
                        {
                            t.HasComment("เตียงผู้ป่วย");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Ipd.DoctorOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorId")
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrderContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer")
                        .HasComment("MEDICATION=1, DIET=2, ACTIVITY=3, INVESTIGATION=4, PROCEDURE=5, OTHER=9");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("ACTIVE=1, COMPLETED=2, CANCELLED=9");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId", "Status");

                    b.ToTable("DoctorOrders", t =>
                        {
                            t.HasComment("คำสั่งแพทย์ (IPD)");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Ipd.NursingNote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NoteType")
                        .HasColumnType("integer")
                        .HasComment("ASSESSMENT=1, INTERVENTION=2, EVALUATION=3, PROGRESS=4");

                    b.Property<string>("RecordedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId", "RecordedDate");

                    b.ToTable("NursingNotes", t =>
                        {
                            t.HasComment("บันทึกการพยาบาล");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Ipd.Ward", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalBeds")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("GENERAL=1, ICU=2, PEDIATRIC=3, SURGICAL=4, OB=5");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Wards", t =>
                        {
                            t.HasComment("หอผู้ป่วย");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Lab.LabOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("PENDING=1, RECEIVED=2, PROCESSING=3, COMPLETED=4, CANCELLED=9");

                    b.HasKey("Id");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.HasIndex("EncounterId", "Status");

                    b.ToTable("LabOrders", t =>
                        {
                            t.HasComment("ใบส่งตรวจทางห้องปฏิบัติการ");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Lab.LabOrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("LabOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceRange")
                        .HasColumnType("text");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LabOrderId");

                    b.ToTable("LabOrderItems", t =>
                        {
                            t.HasComment("รายการตรวจ");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Lab.LabResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EnteredBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsAbnormal")
                        .HasColumnType("boolean");

                    b.Property<string>("LabOrderItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceRange")
                        .HasColumnType("text");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LabOrderItemId")
                        .IsUnique();

                    b.ToTable("LabResults", t =>
                        {
                            t.HasComment("ผลการตรวจ");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.Icd10", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("รหัส เช่น A00, J18.9");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อโรค (ไทย)");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasComment("ชื่อโรค (อังกฤษ)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Icd10s", t =>
                        {
                            t.HasComment("รหัส ICD-10 วินิจฉัยโรค");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.Icd10Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Icd10Categories", t =>
                        {
                            t.HasComment("หมวดหมู่ ICD-10");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.VitalSign", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("BloodPressureDiastolic")
                        .HasColumnType("integer")
                        .HasComment("ความดันโลหิต Diastolic");

                    b.Property<int?>("BloodPressureSystolic")
                        .HasColumnType("integer")
                        .HasComment("ความดันโลหิต Systolic");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Height")
                        .HasColumnType("numeric")
                        .HasComment("ส่วนสูง ซม.");

                    b.Property<int?>("OxygenSaturation")
                        .HasColumnType("integer")
                        .HasComment("ความอิ่มตัวออกซิเจน %");

                    b.Property<int?>("PulseRate")
                        .HasColumnType("integer")
                        .HasComment("ชีพจร ครั้ง/นาที");

                    b.Property<string>("RecordedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasComment("อัตราการหายใจ ครั้ง/นาที");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric")
                        .HasComment("อุณหภูมิ องศาเซลเซียส");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasComment("น้ำหนัก กก.");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.ToTable("VitalSigns", t =>
                        {
                            t.HasComment("สัญญาณชีพ (บันทึกโดยพยาบาล)");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("รหัสผู้ป่วย (UUID)");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date")
                        .HasComment("วันเกิด");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("text")
                        .HasComment("กรุ๊ปเลือด");

                    b.Property<string>("CitizenNo")
                        .HasColumnType("text")
                        .HasComment("เลขบัตรประชาชน 13 หลัก");

                    b.Property<string>("CitizenType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ประเภทบัตร: T=ไทย, F=ต่างชาติ, A=ไม่มีสัญชาติ, N=ไม่มีบัตร");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อ (ไทย)");

                    b.Property<string>("FirstNameEn")
                        .HasColumnType("text")
                        .HasComment("ชื่อ (อังกฤษ)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasComment("เพศ: M=1, F=2, U=3");

                    b.Property<string>("Hn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("หมายเลขผู้ป่วย HN");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("นามสกุล (ไทย)");

                    b.Property<string>("LastNameEn")
                        .HasColumnType("text")
                        .HasComment("นามสกุล (อังกฤษ)");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NationalityCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("สัญชาติ รหัส 3 หลัก (099 = ไทย)");

                    b.Property<string>("Occupation")
                        .HasColumnType("text")
                        .HasComment("อาชีพ");

                    b.Property<string>("PassportNo")
                        .HasColumnType("text")
                        .HasComment("เลขพาสปอร์ต");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasComment("เบอร์โทรศัพท์");

                    b.Property<string>("PreName")
                        .HasColumnType("text")
                        .HasComment("คำนำหน้า (ไทย)");

                    b.Property<string>("PreNameEn")
                        .HasColumnType("text")
                        .HasComment("คำนำหน้า (อังกฤษ)");

                    b.Property<string>("Religion")
                        .HasColumnType("text")
                        .HasComment("ศาสนา");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CitizenNo")
                        .IsUnique()
                        .HasFilter("\"CitizenNo\" IS NOT NULL AND \"DeletedDate\" IS NULL");

                    b.HasIndex("Hn")
                        .IsUnique();

                    b.ToTable("Patients", t =>
                        {
                            t.HasComment("ข้อมูลผู้ป่วย");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.PatientAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ประเภทที่อยู่: HOME, WORK, CURRENT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<string>("SubDistrict")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientAddresses", t =>
                        {
                            t.HasComment("ที่อยู่ผู้ป่วย");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.PatientCoverage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CoverageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayerId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoverageId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PayerId");

                    b.ToTable("PatientCoverages", t =>
                        {
                            t.HasComment("สิทธิการรักษาของผู้ป่วย");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Pharmacy.DrugOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DispensedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorId")
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Running number: RXyyyyMMddNNNNN");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("PENDING=1, VERIFIED=2, DISPENSED=3, CANCELED=9");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.HasIndex("EncounterId", "Status");

                    b.ToTable("DrugOrders", t =>
                        {
                            t.HasComment("ใบสั่งยา");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Pharmacy.DrugOrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DrugOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instruction")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DrugOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("DrugOrderItems");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Product.Pricing", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CoverageId")
                        .HasColumnType("text")
                        .HasComment("สิทธิที่ใช้ราคานี้ (null = ราคา default)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PriceForeign")
                        .HasColumnType("numeric")
                        .HasComment("ราคาต่างชาติ");

                    b.Property<decimal>("PriceNormal")
                        .HasColumnType("numeric")
                        .HasComment("ราคาปกติ");

                    b.Property<decimal>("PriceSpecial")
                        .HasColumnType("numeric")
                        .HasComment("ราคาพิเศษ");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoverageId");

                    b.HasIndex("ProductId");

                    b.ToTable("Pricings", t =>
                        {
                            t.HasComment("ราคาสินค้า/บริการ");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Product.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("ประเภท: MEDICINE=1, SERVICE=2, SUPPLY=3, EQUIPMENT=4, PACKAGE=5");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasComment("หน่วย เช่น เม็ด, ขวด, ครั้ง");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedDate\" IS NULL");

                    b.ToTable("Products", t =>
                        {
                            t.HasComment("สินค้า/บริการ (ยา, หัตถการ, Supplies)");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Queue.QueueItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueueNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("หมายเลขคิว เช่น A001");

                    b.Property<DateTime?>("ServedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("WAITING=1, CALLED=2, SERVING=3, DONE=4, SKIPPED=5");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId")
                        .IsUnique();

                    b.HasIndex("DivisionId", "Status");

                    b.ToTable("QueueItems", t =>
                        {
                            t.HasComment("คิวผู้ป่วย OPD");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Billing.Invoice", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Encounter.Encounter", "Encounter")
                        .WithOne("Invoice")
                        .HasForeignKey("TtssHis.Shared.Entities.Billing.Invoice", "EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Billing.InvoiceItem", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Billing.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TtssHis.Shared.Entities.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Billing.Receipt", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Billing.Invoice", "Invoice")
                        .WithOne("Receipt")
                        .HasForeignKey("TtssHis.Shared.Entities.Billing.Receipt", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.User", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Core.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("TtssHis.Shared.Entities.Core.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Encounter.Diagnosis", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Encounter.Encounter", "Encounter")
                        .WithMany("Diagnoses")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TtssHis.Shared.Entities.Medical.Icd10", "Icd10")
                        .WithMany()
                        .HasForeignKey("Icd10Id");

                    b.Navigation("Encounter");

                    b.Navigation("Icd10");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Encounter.Encounter", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Core.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TtssHis.Shared.Entities.Core.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("TtssHis.Shared.Entities.Patient.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Er.ErTriage", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Encounter.Encounter", "Encounter")
                        .WithOne("ErTriage")
                        .HasForeignKey("TtssHis.Shared.Entities.Er.ErTriage", "EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Insurance.Payer", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Insurance.Coverage", "Coverage")
                        .WithMany("Payers")
                        .HasForeignKey("CoverageId");

                    b.Navigation("Coverage");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Ipd.Bed", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Encounter.Encounter", "CurrentEncounter")
                        .WithMany()
                        .HasForeignKey("CurrentEncounterId");

                    b.HasOne("TtssHis.Shared.Entities.Ipd.Ward", "Ward")
                        .WithMany("Beds")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentEncounter");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Ipd.DoctorOrder", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Encounter.Encounter", "Encounter")
                        .WithMany("DoctorOrders")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Ipd.NursingNote", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Encounter.Encounter", "Encounter")
                        .WithMany("NursingNotes")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Lab.LabOrder", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Encounter.Encounter", "Encounter")
                        .WithMany("LabOrders")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Lab.LabOrderItem", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Lab.LabOrder", "LabOrder")
                        .WithMany("Items")
                        .HasForeignKey("LabOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabOrder");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Lab.LabResult", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Lab.LabOrderItem", "LabOrderItem")
                        .WithOne("Result")
                        .HasForeignKey("TtssHis.Shared.Entities.Lab.LabResult", "LabOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabOrderItem");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.Icd10", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Medical.Icd10Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.Icd10Category", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Medical.Icd10Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.VitalSign", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Encounter.Encounter", "Encounter")
                        .WithMany("VitalSigns")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.PatientAddress", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Patient.Patient", "Patient")
                        .WithMany("Addresses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.PatientCoverage", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Insurance.Coverage", "Coverage")
                        .WithMany()
                        .HasForeignKey("CoverageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TtssHis.Shared.Entities.Patient.Patient", "Patient")
                        .WithMany("Coverages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TtssHis.Shared.Entities.Insurance.Payer", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerId");

                    b.Navigation("Coverage");

                    b.Navigation("Patient");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Pharmacy.DrugOrder", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Encounter.Encounter", "Encounter")
                        .WithMany("DrugOrders")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Pharmacy.DrugOrderItem", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Pharmacy.DrugOrder", "DrugOrder")
                        .WithMany("Items")
                        .HasForeignKey("DrugOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TtssHis.Shared.Entities.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrugOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Product.Pricing", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Insurance.Coverage", "Coverage")
                        .WithMany()
                        .HasForeignKey("CoverageId");

                    b.HasOne("TtssHis.Shared.Entities.Product.Product", "Product")
                        .WithMany("Pricings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coverage");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Queue.QueueItem", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Encounter.Encounter", "Encounter")
                        .WithOne("QueueItem")
                        .HasForeignKey("TtssHis.Shared.Entities.Queue.QueueItem", "EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Billing.Invoice", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Encounter.Encounter", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("DoctorOrders");

                    b.Navigation("DrugOrders");

                    b.Navigation("ErTriage");

                    b.Navigation("Invoice");

                    b.Navigation("LabOrders");

                    b.Navigation("NursingNotes");

                    b.Navigation("QueueItem");

                    b.Navigation("VitalSigns");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Insurance.Coverage", b =>
                {
                    b.Navigation("Payers");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Ipd.Ward", b =>
                {
                    b.Navigation("Beds");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Lab.LabOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Lab.LabOrderItem", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.Icd10Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.Patient", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Pharmacy.DrugOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Product.Product", b =>
                {
                    b.Navigation("Pricings");
                });
#pragma warning restore 612, 618
        }
    }
}
