// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TtssHis.Shared.DbContexts;

#nullable disable

namespace TtssHis.Database.Migrations.Migrations
{
    [DbContext(typeof(HisDbContext))]
    partial class HisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.Division", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("รหัสแผนก (UUID)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("รหัสย่อแผนก เช่น OPD, LAB");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อแผนก (ไทย)");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasComment("ชื่อแผนก (อังกฤษ)");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("ประเภท: OPD=1, IPD=2, ER=3, PHARMACY=4, LAB=5, BILLING=6, OTHER=9");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedDate\" IS NULL");

                    b.ToTable("Divisions", t =>
                        {
                            t.HasComment("แผนก/หน่วยงาน");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.Doctor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("รหัสแพทย์ (UUID)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อ (ไทย)");

                    b.Property<string>("FirstNameEn")
                        .HasColumnType("text")
                        .HasComment("ชื่อ (อังกฤษ)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasComment("เพศ: M=1, F=2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("นามสกุล (ไทย)");

                    b.Property<string>("LastNameEn")
                        .HasColumnType("text")
                        .HasComment("นามสกุล (อังกฤษ)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text")
                        .HasComment("รหัสใบประกอบวิชาชีพ");

                    b.Property<string>("PreName")
                        .HasColumnType("text")
                        .HasComment("คำนำหน้า (ไทย)");

                    b.Property<string>("PreNameEn")
                        .HasColumnType("text")
                        .HasComment("คำนำหน้า (อังกฤษ)");

                    b.Property<string>("Specialty")
                        .HasColumnType("text")
                        .HasComment("ความเชี่ยวชาญ");

                    b.HasKey("Id");

                    b.ToTable("Doctors", t =>
                        {
                            t.HasComment("แพทย์");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("รหัสบทบาท");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("รายละเอียด");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อบทบาท");

                    b.HasKey("Id");

                    b.ToTable("Roles", t =>
                        {
                            t.HasComment("บทบาทผู้ใช้งาน");
                        });

                    b.HasData(
                        new
                        {
                            Id = "role-doctor",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "แพทย์",
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = "role-nurse",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "พยาบาล",
                            Name = "Nurse"
                        },
                        new
                        {
                            Id = "role-pharmacist",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "เภสัชกร",
                            Name = "Pharmacist"
                        },
                        new
                        {
                            Id = "role-finance",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "การเงิน",
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("รหัสผู้ใช้งาน");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorId")
                        .HasColumnType("text")
                        .HasComment("รหัสแพทย์ (ถ้าเป็นหมอ)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อจริง");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("นามสกุล");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("รหัสผ่าน (bcrypt hash)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("รหัสบทบาท");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้ใช้งาน (login)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"DeletedDate\" IS NULL");

                    b.ToTable("Users", t =>
                        {
                            t.HasComment("ผู้ใช้งานระบบ");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Encounter.Diagnosis", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icd10Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("ประเภท: PRINCIPAL=1, COMORBIDITY=2, COMPLICATION=3, RULE_OUT=4");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.HasIndex("Icd10Id");

                    b.ToTable("Diagnoses", t =>
                        {
                            t.HasComment("การวินิจฉัยโรค");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Encounter.Encounter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BedNumber")
                        .HasColumnType("text")
                        .HasComment("เตียง (สำหรับ IPD)");

                    b.Property<string>("ChiefComplaint")
                        .HasColumnType("text")
                        .HasComment("อาการสำคัญ");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorId")
                        .HasColumnType("text");

                    b.Property<string>("EncounterNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("เลข Visit (running number)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("สถานะ: OPEN=1, ADMITTED=2, DISCHARGED=3, CLOSED=4, CANCELED=9");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("ประเภท: OPD=1, IPD=2, ER=3, SS=4");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("EncounterNo")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("Encounters", t =>
                        {
                            t.HasComment("Visit ผู้ป่วย (OPD/IPD)");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Insurance.Coverage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("ประเภทสิทธิ: GOVERNMENT=1, PRIVATE=2, SELF_PAY=3, EMPLOYEE=4");

                    b.HasKey("Id");

                    b.ToTable("Coverages", t =>
                        {
                            t.HasComment("สิทธิการรักษา");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Insurance.Payer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverageId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoverageId");

                    b.ToTable("Payers", t =>
                        {
                            t.HasComment("ผู้รับผิดชอบค่าใช้จ่าย (บริษัทประกัน / ภาครัฐ)");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.Icd10", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("รหัส เช่น A00, J18.9");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อโรค (ไทย)");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasComment("ชื่อโรค (อังกฤษ)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Icd10s", t =>
                        {
                            t.HasComment("รหัส ICD-10 วินิจฉัยโรค");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.Icd10Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Icd10Categories", t =>
                        {
                            t.HasComment("หมวดหมู่ ICD-10");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("รหัสผู้ป่วย (UUID)");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date")
                        .HasComment("วันเกิด");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("text")
                        .HasComment("กรุ๊ปเลือด");

                    b.Property<string>("CitizenNo")
                        .HasColumnType("text")
                        .HasComment("เลขบัตรประชาชน 13 หลัก");

                    b.Property<string>("CitizenType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ประเภทบัตร: T=ไทย, F=ต่างชาติ, A=ไม่มีสัญชาติ, N=ไม่มีบัตร");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อ (ไทย)");

                    b.Property<string>("FirstNameEn")
                        .HasColumnType("text")
                        .HasComment("ชื่อ (อังกฤษ)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasComment("เพศ: M=1, F=2, U=3");

                    b.Property<string>("Hn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("หมายเลขผู้ป่วย HN");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("นามสกุล (ไทย)");

                    b.Property<string>("LastNameEn")
                        .HasColumnType("text")
                        .HasComment("นามสกุล (อังกฤษ)");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NationalityCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("สัญชาติ รหัส 3 หลัก (099 = ไทย)");

                    b.Property<string>("Occupation")
                        .HasColumnType("text")
                        .HasComment("อาชีพ");

                    b.Property<string>("PassportNo")
                        .HasColumnType("text")
                        .HasComment("เลขพาสปอร์ต");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasComment("เบอร์โทรศัพท์");

                    b.Property<string>("PreName")
                        .HasColumnType("text")
                        .HasComment("คำนำหน้า (ไทย)");

                    b.Property<string>("PreNameEn")
                        .HasColumnType("text")
                        .HasComment("คำนำหน้า (อังกฤษ)");

                    b.Property<string>("Religion")
                        .HasColumnType("text")
                        .HasComment("ศาสนา");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CitizenNo")
                        .IsUnique()
                        .HasFilter("\"CitizenNo\" IS NOT NULL AND \"DeletedDate\" IS NULL");

                    b.HasIndex("Hn")
                        .IsUnique();

                    b.ToTable("Patients", t =>
                        {
                            t.HasComment("ข้อมูลผู้ป่วย");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.PatientAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ประเภทที่อยู่: HOME, WORK, CURRENT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<string>("SubDistrict")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientAddresses", t =>
                        {
                            t.HasComment("ที่อยู่ผู้ป่วย");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.PatientCoverage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CoverageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayerId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoverageId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PayerId");

                    b.ToTable("PatientCoverages", t =>
                        {
                            t.HasComment("สิทธิการรักษาของผู้ป่วย");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Product.Pricing", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CoverageId")
                        .HasColumnType("text")
                        .HasComment("สิทธิที่ใช้ราคานี้ (null = ราคา default)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PriceForeign")
                        .HasColumnType("numeric")
                        .HasComment("ราคาต่างชาติ");

                    b.Property<decimal>("PriceNormal")
                        .HasColumnType("numeric")
                        .HasComment("ราคาปกติ");

                    b.Property<decimal>("PriceSpecial")
                        .HasColumnType("numeric")
                        .HasComment("ราคาพิเศษ");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoverageId");

                    b.HasIndex("ProductId");

                    b.ToTable("Pricings", t =>
                        {
                            t.HasComment("ราคาสินค้า/บริการ");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Product.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("ประเภท: MEDICINE=1, SERVICE=2, SUPPLY=3, EQUIPMENT=4, PACKAGE=5");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasComment("หน่วย เช่น เม็ด, ขวด, ครั้ง");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"DeletedDate\" IS NULL");

                    b.ToTable("Products", t =>
                        {
                            t.HasComment("สินค้า/บริการ (ยา, หัตถการ, Supplies)");
                        });
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.User", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Core.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("TtssHis.Shared.Entities.Core.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Encounter.Diagnosis", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Encounter.Encounter", "Encounter")
                        .WithMany("Diagnoses")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TtssHis.Shared.Entities.Medical.Icd10", "Icd10")
                        .WithMany()
                        .HasForeignKey("Icd10Id");

                    b.Navigation("Encounter");

                    b.Navigation("Icd10");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Encounter.Encounter", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Core.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TtssHis.Shared.Entities.Core.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("TtssHis.Shared.Entities.Patient.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Insurance.Payer", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Insurance.Coverage", "Coverage")
                        .WithMany("Payers")
                        .HasForeignKey("CoverageId");

                    b.Navigation("Coverage");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.Icd10", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Medical.Icd10Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.Icd10Category", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Medical.Icd10Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.PatientAddress", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Patient.Patient", "Patient")
                        .WithMany("Addresses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.PatientCoverage", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Insurance.Coverage", "Coverage")
                        .WithMany()
                        .HasForeignKey("CoverageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TtssHis.Shared.Entities.Patient.Patient", "Patient")
                        .WithMany("Coverages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TtssHis.Shared.Entities.Insurance.Payer", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerId");

                    b.Navigation("Coverage");

                    b.Navigation("Patient");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Product.Pricing", b =>
                {
                    b.HasOne("TtssHis.Shared.Entities.Insurance.Coverage", "Coverage")
                        .WithMany()
                        .HasForeignKey("CoverageId");

                    b.HasOne("TtssHis.Shared.Entities.Product.Product", "Product")
                        .WithMany("Pricings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coverage");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Core.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Encounter.Encounter", b =>
                {
                    b.Navigation("Diagnoses");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Insurance.Coverage", b =>
                {
                    b.Navigation("Payers");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Medical.Icd10Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Patient.Patient", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("TtssHis.Shared.Entities.Product.Product", b =>
                {
                    b.Navigation("Pricings");
                });
#pragma warning restore 612, 618
        }
    }
}
